# Vector Algebra - Intro

In [1]:
from numpy import array

In [8]:
v1 = array([1,2,3,4,5])
v2 = array([3,4,6,7,9])

### Vector Arithmetics

In [9]:
v1 + v2

array([ 4,  6,  9, 11, 14])

In [12]:
v2 - v1

array([2, 2, 3, 3, 4])

In [13]:
v1 * v2

array([ 3,  8, 18, 28, 45])

In [14]:
v2 / v1

array([3.  , 2.  , 2.  , 1.75, 1.8 ])

In [16]:
s = 3
s*v1

array([ 3,  6,  9, 12, 15])

In [17]:
v1.dot(v2)

np.int64(102)

In [18]:
def my_dot(a,b):
    sum = 0
    for i,j in zip(a,b):
        sum += i*j
    return sum

my_dot(v1,v2)

np.int64(102)

### Vector Norms
- $L^1$ Norm - $||v||_1$
- $L^2$ norm - $||v||_2$

In [21]:
from numpy.linalg import norm

In [ ]:
v3 = v1 - v2
v3

array([-2, -2, -3, -3, -4])

The $L^1$ norm of $v_3$ is <br>
$||v3||_1 = |a_1| + |a_2| + |a_3| + |a_4| + |a_5|$

In [23]:
v3_norm = norm(v3,1)
v3_norm

np.float64(14.0)

The $L^2$ norm of $v_3$ is <br>
$||v3||_2 = \sqrt{(a_1^2 + a_2^2 + a_3^2 + a_4^2 + a_5^2)}$

In [27]:
v3_norm_2 = norm(v3)
v3_norm_2

np.float64(6.48074069840786)

### Max Norm
We can compute norms to an arbitrary number of values up to infinity. When we get to $L^\infty$, we have what is called the **max norm**.

The $L^n$ of $v_3$ is<br>
$||v3||_n = \sqrt[n]{(a_1^n + a_2^n + a_3^n + a_4^n + a_5^n)}$


In [32]:
norm(v3,4)

np.float64(4.605779351596907)

In [34]:
norm(v3,20)

np.float64(4.00126505813936)

In [31]:
from math import inf
norm(v3,inf)

np.float64(4.0)

In [38]:
print(v2)
norm(v2,inf)

[3 4 6 7 9]


np.float64(9.0)

In [39]:
norm([5,7,11,3,1],inf)

np.float64(11.0)